# Generated by Django 5.1.4 on 2025-08-31 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Магазин',
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, verbose_name='ID товара в МП')),
                ('sku_mp', models.CharField(db_index=True, max_length=150, verbose_name='Артикул в МП')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название в МП')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Штрихкод')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.store')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'indexes': [models.Index(fields=['store', 'sku_mp'], name='api_storepr_store_i_afea54_idx'), models.Index(fields=['store', 'external_id'], name='api_storepr_store_i_b6a532_idx')],
                'unique_together': {('store', 'external_id'), ('store', 'sku_mp')},
            },
        ),
    ]
