# Generated by Django 5.2.5 on 2025-09-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'external_id')},
        ),
    ]
