# Generated by Django 5.2.5 on 2025-09-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_storeproduct_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'external_id'), ('store', 'sku_mp')},
        ),
    ]
